import { Level } from '@prisma/client';

export interface SeedExercise {
  name: string;
  category: string;
  type: string; // gym | calistenia | crossfit | cardio
  level: Level;
  equipment?: string;
  description?: string;
  technique?: string;
  commonMistakes?: string;
  mainMuscles: string[];
  secondaryMuscles: string[];
}

// Catálogo base. Datos y musculatura tomados de la "Guía Completa de Ejercicios"
// (Tabla 1: Gimnasio, Tabla 2: Calistenia, Tabla 3: CrossFit) + ejercicios base.
export const BASE_EXERCISES: SeedExercise[] = [
  // ---------- PECHO ----------
  {
    name: 'Press de banca con barra',
    category: 'pecho',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'barra',
    description: 'Empuje horizontal en decúbito supino; ejercicio rey del pectoral.',
    technique: 'Desciende la barra al esternón de forma controlada y empuja vertical hasta bloquear los codos.',
    commonMistakes: 'Rebotar la barra en el pecho o despegar los glúteos del banco.',
    mainMuscles: ['pectoral mayor'],
    secondaryMuscles: ['deltoides anterior', 'tríceps braquial'],
  },
  {
    name: 'Press inclinado con mancuernas',
    category: 'pecho',
    type: 'gym',
    level: Level.INTERMEDIATE,
    equipment: 'mancuernas',
    description: 'Empuje en banco inclinado que enfatiza la porción clavicular del pectoral.',
    mainMuscles: ['pectoral superior'],
    secondaryMuscles: ['deltoides anterior', 'tríceps braquial'],
  },
  {
    name: 'Floor Press',
    category: 'pecho',
    type: 'gym',
    level: Level.INTERMEDIATE,
    equipment: 'barra',
    description: 'Variante del press tumbado en el suelo; el rango se acorta al contactar los tríceps, enfatizando el bloqueo.',
    mainMuscles: ['tríceps braquial', 'pectoral mayor'],
    secondaryMuscles: ['deltoides anterior'],
  },
  {
    name: 'Press de banca agarre cerrado',
    category: 'pecho',
    type: 'gym',
    level: Level.INTERMEDIATE,
    equipment: 'barra',
    description: 'Manos a la anchura de hombros; minimiza la abducción y carga los extensores del codo.',
    mainMuscles: ['tríceps braquial'],
    secondaryMuscles: ['deltoides anterior', 'porción esternal del pectoral'],
  },
  {
    name: 'Aperturas con mancuernas',
    category: 'pecho',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'mancuernas',
    description: 'Movimiento monoarticular de aducción horizontal con máximo estiramiento del pectoral.',
    mainMuscles: ['pectoral mayor'],
    secondaryMuscles: ['deltoides anterior'],
  },
  {
    name: 'Fondos en paralelas (Dips)',
    category: 'pecho',
    type: 'calistenia',
    level: Level.INTERMEDIATE,
    equipment: 'paralelas',
    description: 'Descenso vertical del tronco suspendido entre barras; el estiramiento pectoral es máximo abajo.',
    mainMuscles: ['pectoral mayor (porción inferior)', 'tríceps braquial'],
    secondaryMuscles: ['deltoides anterior'],
  },

  // ---------- ESPALDA ----------
  {
    name: 'Dominadas',
    category: 'espalda',
    type: 'calistenia',
    level: Level.INTERMEDIATE,
    equipment: 'barra fija',
    description: 'Tracción vertical de cadena cerrada; inicia con depresión y retracción escapular.',
    commonMistakes: 'No completar el rango o balancearse sin control.',
    mainMuscles: ['dorsal ancho', 'redondo mayor'],
    secondaryMuscles: ['bíceps braquial', 'braquial', 'trapecio'],
  },
  {
    name: 'Remo con barra',
    category: 'espalda',
    type: 'gym',
    level: Level.INTERMEDIATE,
    equipment: 'barra',
    description: 'Poliarticular en bisagra de cadera; retracción escapular agresiva traccionando al ombligo.',
    mainMuscles: ['dorsal ancho', 'romboides', 'trapecio'],
    secondaryMuscles: ['deltoides posterior', 'bíceps braquial', 'erectores espinales'],
  },
  {
    name: 'Jalón al pecho (Lat Pulldown)',
    category: 'espalda',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'polea',
    description: 'Tracción vertical en máquina, ideal como progresión hacia la dominada.',
    mainMuscles: ['dorsal ancho'],
    secondaryMuscles: ['bíceps braquial', 'redondo mayor'],
  },
  {
    name: 'Remo invertido (Australian Pull-up)',
    category: 'espalda',
    type: 'calistenia',
    level: Level.BEGINNER,
    equipment: 'barra baja',
    description: 'Tracción horizontal bajo una barra baja con apoyo podal; puente hacia la dominada.',
    mainMuscles: ['dorsal ancho', 'romboides'],
    secondaryMuscles: ['bíceps braquial', 'trapecio medio'],
  },
  {
    name: 'Pullover humano',
    category: 'espalda',
    type: 'calistenia',
    level: Level.ADVANCED,
    equipment: 'barra fija',
    description: 'Jalón con brazos rectos que eleva el cuerpo pivotando en los hombros; aísla los dorsales.',
    mainMuscles: ['dorsal ancho', 'redondo mayor'],
    secondaryMuscles: ['tríceps (porción larga)', 'core'],
  },
  {
    name: 'Face pull',
    category: 'espalda',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'polea',
    description: 'Tracción a la cara para el deltoides posterior y la salud del hombro.',
    mainMuscles: ['deltoides posterior', 'trapecio'],
    secondaryMuscles: ['romboides'],
  },

  // ---------- PIERNAS ----------
  {
    name: 'Sentadilla con barra',
    category: 'piernas',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'barra',
    description: 'Rey de los ejercicios de tren inferior; triple flexo-extensión de tobillo, rodilla y cadera.',
    technique: 'Barra sobre el trapecio, desciende hasta romper la paralela manteniendo la espalda neutra.',
    commonMistakes: 'Valgo de rodillas o levantar los talones.',
    mainMuscles: ['cuádriceps', 'glúteo mayor'],
    secondaryMuscles: ['isquiosurales', 'core'],
  },
  {
    name: 'Sentadilla frontal (Front Squat)',
    category: 'piernas',
    type: 'gym',
    level: Level.INTERMEDIATE,
    equipment: 'barra',
    description: 'Barra sobre las clavículas; mayor demanda de cuádriceps y torso erguido.',
    mainMuscles: ['cuádriceps', 'glúteo mayor'],
    secondaryMuscles: ['erectores espinales', 'core'],
  },
  {
    name: 'Peso muerto convencional',
    category: 'piernas',
    type: 'gym',
    level: Level.ADVANCED,
    equipment: 'barra',
    description: 'Tracción de peso libre desde el suelo extendiendo caderas y rodillas.',
    commonMistakes: 'Redondear la zona lumbar bajo carga.',
    mainMuscles: ['isquiosurales', 'glúteo mayor', 'erectores espinales'],
    secondaryMuscles: ['dorsal ancho', 'trapecio'],
  },
  {
    name: 'Prensa de piernas',
    category: 'piernas',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'máquina',
    description: 'Empuje de piernas en máquina, estable y apto para cargas altas.',
    mainMuscles: ['cuádriceps'],
    secondaryMuscles: ['glúteo mayor'],
  },
  {
    name: 'Sentadilla búlgara',
    category: 'piernas',
    type: 'gym',
    level: Level.INTERMEDIATE,
    equipment: 'mancuernas',
    description: 'Sentadilla a una pierna con la contralateral elevada; gran estiramiento y estabilización pélvica.',
    mainMuscles: ['cuádriceps', 'glúteo mayor'],
    secondaryMuscles: ['isquiosurales', 'estabilizadores de cadera'],
  },
  {
    name: 'Curl nórdico',
    category: 'piernas',
    type: 'gym',
    level: Level.ADVANCED,
    description: 'Estímulo excéntrico supramáximo de isquios; profilaxis frente a desgarros.',
    mainMuscles: ['isquiosurales (bíceps femoral, semitendinoso, semimembranoso)'],
    secondaryMuscles: ['gemelos'],
  },
  {
    name: 'Good Morning',
    category: 'piernas',
    type: 'gym',
    level: Level.INTERMEDIATE,
    equipment: 'barra',
    description: 'Flexión de cadera con barra en la espalda; recluta toda la cadena posterior.',
    mainMuscles: ['glúteo mayor', 'isquiosurales', 'erectores espinales'],
    secondaryMuscles: ['core'],
  },
  {
    name: 'Zancadas (Lunges)',
    category: 'piernas',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'mancuernas',
    description: 'Patrón unilateral de zancada que desarrolla volumen base y equilibrio.',
    mainMuscles: ['cuádriceps', 'glúteo mayor'],
    secondaryMuscles: ['isquiosurales', 'gemelos'],
  },
  {
    name: 'Hip thrust',
    category: 'piernas',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'barra',
    description: 'Extensión de cadera con la espalda apoyada; máxima activación del glúteo.',
    mainMuscles: ['glúteo mayor'],
    secondaryMuscles: ['isquiosurales'],
  },
  {
    name: 'Pistol squat',
    category: 'piernas',
    type: 'calistenia',
    level: Level.ADVANCED,
    description: 'Sentadilla unilateral sin apoyo; requiere profunda dorsiflexión y compresión anterior.',
    mainMuscles: ['cuádriceps', 'glúteo mayor'],
    secondaryMuscles: ['isquiosurales', 'gemelos', 'tibial anterior'],
  },
  {
    name: 'Elevaciones de gemelo',
    category: 'piernas',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'máquina',
    description: 'Flexión plantar desde déficit para estirar el tríceps sural.',
    mainMuscles: ['gastrocnemio', 'sóleo'],
    secondaryMuscles: [],
  },

  // ---------- HOMBROS ----------
  {
    name: 'Press militar con barra',
    category: 'hombros',
    type: 'gym',
    level: Level.INTERMEDIATE,
    equipment: 'barra',
    description: 'Empuje vertical estricto de la barra hasta bloquear codos por encima de la cabeza.',
    mainMuscles: ['deltoides anterior'],
    secondaryMuscles: ['deltoides lateral', 'tríceps braquial'],
  },
  {
    name: 'Elevaciones laterales',
    category: 'hombros',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'mancuernas',
    description: 'Abducción glenohumeral monoarticular para el deltoides medio.',
    mainMuscles: ['deltoides lateral'],
    secondaryMuscles: [],
  },
  {
    name: 'Elevaciones laterales con polea',
    category: 'hombros',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'polea',
    description: 'Curva de resistencia continua superior a las mancuernas, con torque constante en el estiramiento.',
    mainMuscles: ['deltoides medio', 'supraespinoso'],
    secondaryMuscles: ['trapecio superior'],
  },
  {
    name: 'Pájaros (elevaciones posteriores)',
    category: 'hombros',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'mancuernas',
    description: 'Aislamiento del deltoides posterior en bisagra de cadera.',
    mainMuscles: ['deltoides posterior'],
    secondaryMuscles: ['romboides', 'trapecio'],
  },

  // ---------- BÍCEPS ----------
  {
    name: 'Curl con barra',
    category: 'biceps',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'barra',
    description: 'Flexión aislada del codo; la supinación maximiza el acortamiento del bíceps.',
    mainMuscles: ['bíceps braquial'],
    secondaryMuscles: ['braquial anterior', 'braquiorradial'],
  },
  {
    name: 'Curl con mancuernas',
    category: 'biceps',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'mancuernas',
    description: 'Curl alterno con supinación para trabajar cada brazo de forma independiente.',
    mainMuscles: ['bíceps braquial'],
    secondaryMuscles: ['braquial anterior'],
  },
  {
    name: 'Curl martillo',
    category: 'biceps',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'mancuernas',
    description: 'Agarre neutro que enfatiza el braquiorradial y el grosor del brazo.',
    mainMuscles: ['braquiorradial', 'bíceps braquial'],
    secondaryMuscles: ['braquial anterior'],
  },

  // ---------- TRÍCEPS ----------
  {
    name: 'Press francés con mancuernas',
    category: 'triceps',
    type: 'gym',
    level: Level.INTERMEDIATE,
    equipment: 'mancuernas',
    description: 'Flexo-extensión del codo en supino con hombros a 90°; máximo estiramiento de la cabeza larga.',
    mainMuscles: ['tríceps braquial (cabeza larga)'],
    secondaryMuscles: ['ancóneo'],
  },
  {
    name: 'Pressdown (jalón de tríceps)',
    category: 'triceps',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'polea',
    description: 'Extensión de codo con los codos anclados a las costillas; estrés metabólico focalizado.',
    mainMuscles: ['tríceps braquial (cabeza lateral y medial)'],
    secondaryMuscles: ['ancóneo'],
  },
  {
    name: 'Extensión de tríceps sobre la cabeza',
    category: 'triceps',
    type: 'gym',
    level: Level.BEGINNER,
    equipment: 'polea',
    description: 'Hombro en máxima flexión que somete la cabeza larga a su máxima longitud operativa.',
    mainMuscles: ['tríceps braquial (cabeza larga)'],
    secondaryMuscles: [],
  },

  // ---------- ABDOMEN / CORE ----------
  {
    name: 'Plancha abdominal',
    category: 'abdomen',
    type: 'calistenia',
    level: Level.BEGINNER,
    description: 'Isométrico prono que estabiliza la pelvis; mantener el cuerpo como una tabla.',
    mainMuscles: ['recto abdominal', 'transverso del abdomen'],
    secondaryMuscles: ['oblicuos', 'erectores lumbares'],
  },
  {
    name: 'Hollow hold',
    category: 'abdomen',
    type: 'calistenia',
    level: Level.INTERMEDIATE,
    description: 'Retención isométrica que aplasta la lumbar contra el suelo; base gimnástica del core.',
    mainMuscles: ['recto abdominal', 'transverso del abdomen'],
    secondaryMuscles: ['flexores de cadera', 'cuádriceps'],
  },
  {
    name: 'L-Sit',
    category: 'abdomen',
    type: 'calistenia',
    level: Level.ADVANCED,
    equipment: 'paralelas',
    description: 'Suspensión del cuerpo en "L" que exige compresión extrema de abdomen y cuádriceps.',
    mainMuscles: ['recto abdominal', 'flexores de cadera'],
    secondaryMuscles: ['cuádriceps', 'tríceps'],
  },
  {
    name: 'Dragon Flag',
    category: 'abdomen',
    type: 'calistenia',
    level: Level.ADVANCED,
    equipment: 'banco',
    description: 'Se eleva el cuerpo recto pivotando sobre la escápula; combina acciones isométricas severas y control excéntrico.',
    commonMistakes: 'Hiperextender la lumbar (postura "banana") en lugar de retroversión pélvica.',
    mainMuscles: ['recto abdominal', 'oblicuos'],
    secondaryMuscles: ['dorsal ancho', 'psoas ilíaco', 'glúteo mayor'],
  },
  {
    name: 'Elevaciones de piernas colgado',
    category: 'abdomen',
    type: 'calistenia',
    level: Level.INTERMEDIATE,
    equipment: 'barra fija',
    description: 'Suspendido de la barra, eleva las piernas con retroversión pélvica activa.',
    mainMuscles: ['recto abdominal', 'flexores de cadera'],
    secondaryMuscles: ['oblicuos'],
  },

  // ---------- CALISTENIA (empuje / avanzados) ----------
  {
    name: 'Flexiones clásicas (Push-ups)',
    category: 'calistenia',
    type: 'calistenia',
    level: Level.BEGINNER,
    description: 'Empuje horizontal en plancha con alineación isométrica de la columna.',
    mainMuscles: ['pectoral mayor', 'deltoides anterior', 'tríceps braquial'],
    secondaryMuscles: ['core'],
  },
  {
    name: 'Flexiones diamante',
    category: 'calistenia',
    type: 'calistenia',
    level: Level.INTERMEDIATE,
    description: 'Manos en rombo que transfieren la carga extensora al tríceps.',
    mainMuscles: ['tríceps braquial'],
    secondaryMuscles: ['deltoides anterior', 'porción esternal del pectoral'],
  },
  {
    name: 'Flexiones arquero',
    category: 'calistenia',
    type: 'calistenia',
    level: Level.ADVANCED,
    description: 'Un brazo empuja el ~80% de la carga mientras el otro asiste lateralmente.',
    mainMuscles: ['pectoral mayor (unilateral)', 'tríceps braquial'],
    secondaryMuscles: ['deltoides anterior'],
  },
  {
    name: 'Pike push-up',
    category: 'calistenia',
    type: 'calistenia',
    level: Level.INTERMEDIATE,
    description: 'Cadera elevada en "V" invertida que simula un press vertical con peso corporal.',
    mainMuscles: ['deltoides anterior', 'deltoides medio'],
    secondaryMuscles: ['tríceps braquial', 'porción clavicular del pectoral'],
  },
  {
    name: 'Handstand push-up (HSPU)',
    category: 'calistenia',
    type: 'calistenia',
    level: Level.ADVANCED,
    equipment: 'pared',
    description: 'Flexión en posición de pino invertido; fuerza superlativa de hombro y control propioceptivo.',
    mainMuscles: ['deltoides (todas las cabezas)', 'tríceps braquial'],
    secondaryMuscles: ['trapecio superior'],
  },
  {
    name: 'Muscle-up',
    category: 'calistenia',
    type: 'calistenia',
    level: Level.ADVANCED,
    equipment: 'barra o anillas',
    description: 'Une una dominada explosiva con un fondo de transición para superar el punto de estancamiento.',
    mainMuscles: ['dorsal ancho', 'pectoral', 'tríceps braquial'],
    secondaryMuscles: ['bíceps braquial', 'deltoides', 'core'],
  },
  {
    name: 'Front Lever',
    category: 'calistenia',
    type: 'calistenia',
    level: Level.ADVANCED,
    equipment: 'barra fija',
    description: 'Suspensión estática horizontal cara arriba; el cuerpo actúa como palanca de tercer género.',
    mainMuscles: ['dorsal ancho', 'redondo mayor'],
    secondaryMuscles: ['tríceps (porción larga)', 'core'],
  },
  {
    name: 'Back Lever',
    category: 'calistenia',
    type: 'calistenia',
    level: Level.ADVANCED,
    equipment: 'barra fija',
    description: 'Suspensión estática horizontal cara abajo asido a la barra o anillas.',
    mainMuscles: ['erectores espinales', 'pectoral'],
    secondaryMuscles: ['deltoides', 'bíceps braquial'],
  },
  {
    name: 'Planche',
    category: 'calistenia',
    type: 'calistenia',
    level: Level.ADVANCED,
    description: 'Sostiene el cuerpo paralelo al suelo apoyado solo en las manos.',
    mainMuscles: ['deltoides anterior', 'pectoral'],
    secondaryMuscles: ['tríceps braquial', 'core', 'serrato anterior'],
  },

  // ---------- CARDIO / METABÓLICO ----------
  {
    name: 'Carrera continua',
    category: 'cardio',
    type: 'cardio',
    level: Level.BEGINNER,
    description: 'Trabajo aeróbico continuo de intensidad moderada.',
    mainMuscles: ['sistema cardiovascular'],
    secondaryMuscles: ['cuádriceps', 'gemelos'],
  },
  {
    name: 'Mountain climbers',
    category: 'cardio',
    type: 'cardio',
    level: Level.BEGINNER,
    description: 'Movimiento cíclico sin carga para acelerar el metabolismo y trabajar el core.',
    mainMuscles: ['flexores de cadera', 'core'],
    secondaryMuscles: ['sistema cardiovascular', 'sóleo'],
  },
  {
    name: 'Jumping jacks',
    category: 'cardio',
    type: 'cardio',
    level: Level.BEGINNER,
    description: 'Salto de tijera para elevar la frecuencia cardíaca y coordinación rítmica.',
    mainMuscles: ['sistema cardiovascular'],
    secondaryMuscles: ['deltoides', 'gemelos'],
  },
  {
    name: 'Comba (Double Unders)',
    category: 'cardio',
    type: 'crossfit',
    level: Level.INTERMEDIATE,
    equipment: 'comba',
    description: 'Doble paso de cuerda por salto; alta demanda de coordinación óculo-manual.',
    mainMuscles: ['gemelos', 'sóleo', 'antebrazos'],
    secondaryMuscles: ['sistema cardiovascular'],
  },
  {
    name: 'Remo en máquina (Rowing erg)',
    category: 'cardio',
    type: 'cardio',
    level: Level.BEGINNER,
    equipment: 'máquina de remo',
    description: 'Ciclismo aeróbico/anaeróbico de cuerpo completo con la cadena de tracción.',
    mainMuscles: ['dorsal ancho', 'cuádriceps'],
    secondaryMuscles: ['sistema cardiovascular', 'antebrazos'],
  },

  // ---------- CROSSFIT / HÍBRIDO ----------
  {
    name: 'Sentadilla overhead (OHS)',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.ADVANCED,
    equipment: 'barra',
    description: 'Sentadilla con la barra bloqueada por encima de la cabeza; exige movilidad y estabilidad total.',
    mainMuscles: ['cuádriceps', 'glúteos'],
    secondaryMuscles: ['estabilizadores de hombro', 'core'],
  },
  {
    name: 'Push press',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.INTERMEDIATE,
    equipment: 'barra',
    description: 'Press de hombros con impulso inicial de piernas para mover más carga.',
    mainMuscles: ['deltoides', 'tríceps braquial'],
    secondaryMuscles: ['cuádriceps', 'glúteos'],
  },
  {
    name: 'Push jerk',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.ADVANCED,
    equipment: 'barra',
    description: 'Impulso de piernas y recepción en semi-sentadilla bajo la barra.',
    mainMuscles: ['deltoides', 'tríceps braquial'],
    secondaryMuscles: ['cuádriceps', 'glúteos'],
  },
  {
    name: 'Clean (cargada)',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.ADVANCED,
    equipment: 'barra',
    description: 'Lleva la barra a los hombros mediante extensión explosiva de cadera y rack frontal rápido.',
    mainMuscles: ['cuádriceps', 'glúteos', 'trapecios'],
    secondaryMuscles: ['erectores espinales', 'deltoides', 'tríceps'],
  },
  {
    name: 'Snatch (arrancada)',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.ADVANCED,
    equipment: 'barra',
    description: 'Arrancada olímpica del suelo al bloqueo superior en un solo movimiento balístico.',
    mainMuscles: ['extensores de cadera', 'trapecios', 'deltoides'],
    secondaryMuscles: ['tríceps braquial', 'cuádriceps'],
  },
  {
    name: 'Muscle snatch',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.ADVANCED,
    equipment: 'barra',
    description: 'Arrancada sin re-flexionar las rodillas; construye fuerza y estabilidad del tren superior.',
    mainMuscles: ['trapecio superior', 'deltoides medio y posterior'],
    secondaryMuscles: ['tríceps braquial', 'erectores espinales'],
  },
  {
    name: 'Sots Press',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.ADVANCED,
    equipment: 'barra',
    description: 'Press estricto desde la posición más profunda de la sentadilla; revela restricciones de movilidad.',
    mainMuscles: ['deltoides', 'tríceps braquial'],
    secondaryMuscles: ['erectores espinales profundos', 'estabilizadores pélvicos'],
  },
  {
    name: 'Thruster',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.INTERMEDIATE,
    equipment: 'barra',
    description: 'Sentadilla frontal encadenada sin pausa a un push press; devastador para el metabolismo.',
    mainMuscles: ['cuádriceps', 'glúteos', 'deltoides anterior'],
    secondaryMuscles: ['isquiosurales', 'tríceps braquial', 'core'],
  },
  {
    name: "Devil's Press",
    category: 'crossfit',
    type: 'crossfit',
    level: Level.ADVANCED,
    equipment: 'mancuernas',
    description: 'Une un burpee sobre mancuernas con una arrancada doble simultánea hasta el bloqueo superior.',
    mainMuscles: ['cadena posterior', 'glúteos', 'pectorales'],
    secondaryMuscles: ['deltoides', 'tríceps braquial'],
  },
  {
    name: 'Wall Balls',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.BEGINNER,
    equipment: 'balón medicinal',
    description: 'Front squat fluido seguido de un lanzamiento del balón a un objetivo alto.',
    mainMuscles: ['cuádriceps', 'glúteos', 'deltoides'],
    secondaryMuscles: ['core', 'tríceps braquial'],
  },
  {
    name: 'Sumo Deadlift High Pull (SDHP)',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.INTERMEDIATE,
    equipment: 'barra',
    description: 'Peso muerto sumo con tirón alto que eleva la barra hasta la barbilla.',
    mainMuscles: ['isquiosurales', 'glúteos', 'trapecios'],
    secondaryMuscles: ['deltoides anterior', 'cuádriceps'],
  },
  {
    name: 'Burpee',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.BEGINNER,
    description: 'Caída al suelo, flexión, reincorporación explosiva y salto; acondicionamiento de cuerpo completo.',
    mainMuscles: ['pectoral', 'tríceps braquial', 'cuádriceps', 'glúteos'],
    secondaryMuscles: ['sistema cardiorrespiratorio'],
  },
  {
    name: 'Box jumps',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.BEGINNER,
    equipment: 'cajón',
    description: 'Salto pliométrico a un cajón que entrena la tasa de desarrollo de fuerza (RFD).',
    mainMuscles: ['cuádriceps', 'glúteos', 'gemelos'],
    secondaryMuscles: ['sistema cardiovascular'],
  },
  {
    name: 'Toes-to-bar',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.INTERMEDIATE,
    equipment: 'barra fija',
    description: 'Balanceo arch-hollow para llevar los pies a la barra; línea media dinámica.',
    mainMuscles: ['recto abdominal', 'flexores de cadera'],
    secondaryMuscles: ['dorsal ancho', 'deltoides'],
  },
  {
    name: 'GHD Sit-Up',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.ADVANCED,
    equipment: 'máquina GHD',
    description: 'Flexión dinámica de tronco de gran amplitud; catapulta el torso con extensión de cuádriceps.',
    commonMistakes: 'Flexionar la columna pasivamente en lugar de extender las rodillas de golpe.',
    mainMuscles: ['recto abdominal', 'recto femoral', 'psoas mayor'],
    secondaryMuscles: ['oblicuos', 'cuádriceps'],
  },
  {
    name: 'Rope climb',
    category: 'crossfit',
    type: 'crossfit',
    level: Level.INTERMEDIATE,
    equipment: 'cuerda',
    description: 'Trepa de cuerda que exige fuerza de agarre extrema y tracción.',
    mainMuscles: ['antebrazos', 'dorsal ancho', 'bíceps braquial'],
    secondaryMuscles: ['cadena posterior', 'core'],
  },

  // ---------- MOVILIDAD ----------
  {
    name: 'Sentadilla profunda (movilidad)',
    category: 'movilidad',
    type: 'calistenia',
    level: Level.BEGINNER,
    description: 'Mantenimiento en sentadilla profunda para movilidad de cadera y tobillo.',
    mainMuscles: ['cadera', 'tobillos'],
    secondaryMuscles: ['aductores'],
  },
  {
    name: 'Gato-camello (Cat-Cow)',
    category: 'movilidad',
    type: 'calistenia',
    level: Level.BEGINNER,
    description: 'Movilización espinal en cuadrupedia alternando flexión y extensión.',
    mainMuscles: ['columna vertebral'],
    secondaryMuscles: ['core'],
  },
];
